### ISSUE TITLE
Unable to run uperf with sample from docs

### ISSUE THREAD

**Issue by kpouget** [cloud-bulldozer/benchmark-operator#415]
The `uperf` [documentation](https://github.com/cloud-bulldozer/benchmark-operator/blob/9c483ec/docs/uperf.md) gives this simple YAML file:
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: my-ripsaw
spec:
  workload:
    name: uperf
    args:
      client_resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi
      server_resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi
      serviceip: false
      runtime_class: class_name
      hostnetwork: false
      pin: false
      kind: pod
      pin_server: "node-0"
      pin_client: "node-1"
      multus:
        enabled: false
      samples: 1
      pair: 1
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30
```
but this CR fails to execute.

From what I could understand in the logs, the issue is:
```
Job.batch "uperf-server-0-b7e20b49" is invalid: spec.template.spec.runtimeClassName: Invalid value: "class_name": a DNS-1123 subdomain must consist of lower case alphanumeric characters ...
```
Removing `runtime_class: class_name` solves the problem.
