### ISSUE TITLE
[Enhancement] Add "BenchmarkSuite" CRD

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/benchmark-operator#465]
Proposal:

Ripsaw should be able to accept a `BenchmarkSuite` CRD, which contains definitions to a list of benchmarks to run. The CRD would be able to maintain all shared values across benchmarks, such as run_id and Metadata Collection/ES configuration

Example:

```yaml
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: BenchmarkSuite
spec:
  run_id: global_run_id
  execution: parallel | serial 
  metadata:
    # Metadata stuff here, defined once.
  defaults:
     nodeSelector: {} # would be useful to force all benchmarks onto one node type by default 
  workloads: 
    - name: scale
      type: scale
      args: []
    - name: uperf-run
      type: uperf
      dependsOn: scale # would only run if the scale test passed, and would force this benchmark to wait until scale completes successfully, even in parallel
      args:[]
    - name: my-bench
      type: byowl
      args: []


```
