### ISSUE TITLE
[uperf] Uperf pod placement at scale based on number of nodes

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/benchmark-operator#476]
Currently within the CR for uperf, we have a way to ping the server pods and client pods using a nodeSelector like in https://github.com/cloud-bulldozer/benchmark-operator/blob/master/resources/crds/ripsaw_v1alpha1_uperf_cr.yaml#L22-L23.

However, we also need another dimension to run uperf at scale and some of the requirements are
1. If I want to run 20 uperf pairs, I need exactly the same number of servers/clients per node (uniform placement). This as I understand cannot just be guaranteed by pin_server/pin_client as a non-uniform number of server/client pods can end up on the nodes matching the label specified by nodeSelectors.
2. We need an easy way to scale the test up, like say a parameter in the CR like `num_nodes` which would do the math internally and scale up the test with the given parameters.

I will leave this issue open to discussion and would like to hear thoughts from others as well. Thanks!

**Comment by smalleni** [comment]
@jtaleric @dustinblack Let's discuss more here.

**Comment by smalleni** [comment]
So I have some ideas and would like to use them as a starting point. This is based on my previous experience running dataplane tests at scale on OpenStack. The general methodology should apply to OpenShift, regardless.

This is my proposed ripsaw uperf CR
```apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: my-ripsaw
spec:
  clustername: myk8scluster
  #elasticsearch:
  #   server: elk.server.com
  #   port: 9200
  #test_user: username_to_attach_to_metadata
  workload:
    # cleanup: true
    name: uperf
    args:
      serviceip: false
      hostnetwork: false
      networkpolicy: false
      pin: false
      multus:
        enabled: false
     # pin_server: "node-0"
     # pin_client: "node-1"
      samples: 1
      kind: pod
      execution: linear
      worker_nodes: 10
      accomodation: colocated
      density: 10
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30```

The idea is to scale the test from bottom up, define the test in terms of what you want to happen in terms of 1-2 worker nodes and scale that up/multiply.

The accommodation parameter takes two values
1. colocated -  The server/client are placed on the same worker node (so two pods per worker node)
2. separate - The server and the corresponding client are placed on separate worker nodes (so one pod per worker node)

The density parameter is a multiplier for the number of instances per worker node. Let's say density is 10, then we mean to have 10 server/client pairs per worker node in the case of `colocated` accommodation scenario and 10 server pods and 10 client pods spread across 2 worker nodes ( with servers and clients on separate nodes , so we will totally have 50 server pods and 50 client pods spread across 10 nodes) in the case of `separate` accommodation scenario (there by using all 10 required worker nodes bu putting servers and clients on separate nodes.

The `execution` parameter should take the values on `none`, `linear` or `quadratic`. That would mean, if based on the the accommodation, density and worker node count, we end up with 10 server/client pods, the test would be executed with all 10 pairs at once if the execution strategy is `none` and will step up from 1 to 10 linearly if it is `linear` and will take a quadratic progression if `quadratic`.

This would also mean we get rid of the `pairs` parameter in uperf CR as we are now defining with a more complex set of parameters.

So by using, `accommodation`, `density`, `progression` and `worker_nodes` parameters we will be able to scale up the dataplane testing. We would execute all protocols, message sizes and thread numbers for each iteration of the execution.

For example, if I have

` ``    execution: none
      worker_nodes: 10
      accomodation: colocated
      density: 10
      test_types:
        - stream
      protos:
        - tcp
        - udp
      sizes:
        - 1024
        - 16384
      nthrs:
        - 1
        - 2
```

Here's what would happen

We would launch 10 servers and 10 clients per worker node across 10  worker nodes for a total of 100 server/client pairs.
It would then execute the uperf tests (all protocols, message sizes and threads serially) across the 100 pairs at once (no progression since we chose the execution strategy to be none)

` `` 
      execution: quadratic
      worker_nodes: 4
      accomodation: separate
      density: 10
      test_types:
        - stream
      protos:
        - tcp
        - udp
      sizes:
        - 1024
        - 16384
      nthrs:
        - 1
        - 2
```
 In the above scenario, 20 servers will be placed across two worker nodes and 20 clients will be placed against the other 2 worker nodes. For each progression, the test is executed against 1 pair of pods, then 2 pairs, then 4, then 8...so on until it hits the maximum possible quadratically. At each iteration of the execution, for example lets say at 8 pod pairs, all the tests (all combinations of threads, message sizes, protocols and test_types are executed).

This along with https://github.com/cloud-bulldozer/benchmark-operator/issues/473, https://github.com/cloud-bulldozer/benchmark-operator/issues/474 and https://github.com/cloud-bulldozer/benchmark-operator/issues/475 should help prepare us for dataplane testing at scale.

**Comment by smalleni** [comment]
@rsevilla87 thoughts?

**Comment by dustinblack** [comment]
For some consistency across workloads, I would recommend modeling the `execution` parameter here and the `num_databases_pattern` from the pgbench workload to work effectively the same way. I wouldn't want to dictate that the way I did this with pgbench is the right way and we should do it the same here, rather if we find a better way here we should also apply it to pgbench and use it as a general reference model for other workloads that might want scaling patterns up to some N level of scale (possibly even introduce some resuable code at a higher level of the benchmark operator).

https://github.com/cloud-bulldozer/benchmark-operator/blob/399574c0b4a2b311efdffffa8b7e5da7c36e7aaf/resources/crds/ripsaw_v1alpha1_pgbench_cr.yaml#L45

```yaml
      # num_databases_pattern takes a pattern definition, one of:
      # 'add1' (1,2,3,...), 'add2' (2,4,6,...), 'log2' (1,2,4,8,...), or 'all'
      # The default if left blank or undefined is 'all'
      num_databases_pattern: 'all'
```

https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/pgbench/tasks/generate_num_databases.yml

```yaml
---
- name: Set num_databases for add1
  set_fact:
    num_databases: "{{ num_databases|default([]) + [(item.0|int + 1)] }}"
  with_indexed_items: "{{ workload_args.databases }}"
  when: num_databases_pattern == "add1"

- name: Set num_databases for add2
  set_fact:
    num_databases: "{{ num_databases|default([]) + [(item.0|int + 1)] }}"
  with_indexed_items: "{{ workload_args.databases }}"
  when: num_databases_pattern == "add2" and item.0|int is odd

- name: Set num_databases for log2
  set_fact:
    num_databases: "{{ num_databases|default([]) + [(item.0|int + 1)] }}"
  with_indexed_items: "{{ workload_args.databases }}"
  when: num_databases_pattern == "log2" and (((item.0|int + 1)|log(2)) is even or ((item.0|int + 1)|log(2)) is odd)

- name: Set num_databases for all
  set_fact:
    num_databases: "{{ num_databases|default([]) + [workload_args.databases|length] }}"
  when: num_databases_pattern == "all"
```
