### ISSUE TITLE
Implement operator loop state tasks as a "library" item

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/benchmark-operator#496]
The tasks for operator loop state detection have become boilerplate across the workload roles. I think we should consider moving this into the "common" role and importing the tasks as effectively "library" items into the workload `tasks/main.yml` playbooks.

Ultimately, I think a lot of workload role functionality ends up being reusable, and it would be nice to see other functionality get moved into the "common" role. These loop state tasks should be fairly low effort and straightforward to convert to this "library" approach and can serve as a template for how this can be leveraged for other functionality.

```yaml
- name: Get current state
  k8s_info:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: '{{ meta.name }}'
    namespace: '{{ operator_namespace }}'
  register: resource_state

- operator_sdk.util.k8s_status:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
    status:
      state: Building
      complete: false
  when: resource_state.resources[0].status.state is not defined

- name: Get current state - If it has changed
  k8s_info:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: '{{ meta.name }}'
    namespace: '{{ operator_namespace }}'
  register: resource_state
```
