### ISSUE TITLE
elasticsearch.url field ignored or dropped in benchmark build

### ISSUE THREAD

**Issue by martineg** [cloud-bulldozer/benchmark-operator#515]
Running the benchmark-operator installed from the Helm chart in master, I'm dealing with an issue of the `elasticsearch.url` parameter I pass in the benchmark CR somehow being silently dropped and causing errors in the benchmark build.

Excerpt from my benchmark CR is as follows:
```yaml
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-pod2pod
  namespace: my-ripsaw
spec:
  elasticsearch:
    url: "http://svc-http-elasticsearch:9200"
  workload:
    name: uperf
    args:
...
```

However my benchmark is stuck in state "Starting Clients", and with the following error in the ansible log of the operator pod:
```
TASK [uperf : Start Client(s)] *************************************************
task path: /opt/ansible/roles/uperf/tasks/main.yml:178
looking for "workload.yml.j2" at "/opt/ansible/roles/uperf/templates/workload.yml.j2"
File lookup using /opt/ansible/roles/uperf/templates/workload.yml.j2 as file
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to be in '/opt/ansible/roles/uperf/tasks/main.yml': line 178, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  - block:\n    - name: Start Client(s)\n      ^ here\n"
}
```

Reviewing the Benchmark object shows that the elasticsearch.url field is set in the applied configuration annotation, however is empty in the object itself. 
```
$ oc get benchmark uperf-pod2pod -o yaml
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ripsaw.cloudbulldozer.io/v1alpha1","kind":"Benchmark","metadata":{"annotations":{},"name":"uperf-pod2pod","namespace":"my-ripsaw"},"spec":"elasticsearch":{"url":"http://svc-http-elasticsearch:9200"} ....
..
spec:
  cerberus_url: http://cerberus.cerberus.svc.cluster.local:8080
  elasticsearch: {}
```
