### ISSUE TITLE
BYOWL: Need support for POD privileged mode, hostPath access, mountPath

### ISSUE THREAD

**Issue by asispatra** [cloud-bulldozer/benchmark-operator#533]
Currently BYOWL does not allow to run POD in privileged mode, hostPath access, mountPath, etc properties. 

Can add support for these and all possible properties in BYOWL, so that we can use BYOWL for any workload which can run in privileged mode and should have access to hostPath etc.

Currently I have hard coded these option in the `roles/byowl/templates/workload.yml` and building the `benchmark-operator` myself.

If we add all possible properties support in BYOWL, individual do not need to build the `benchmark-operator` themselves.

Thanks.

**Comment by rsevilla87** [comment]
If you feel comfortable enough, feel free to send a PR including these features, I'll try to help you to get it merged asap.

**Comment by asispatra** [comment]
Here are the changes we have made in `roles/byowl/templates/workload.yml` under `workload_args.privileged` condition to enable privileged mode, hostPath access and mountPath.
```
apiVersion: batch/v1
kind: "job"
metadata:
  name: "byowl-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: byowl-{{ trunc_uuid }}
    spec:
{% if workload_args.privileged is sameas true %}
      serviceAccountName: benchmark-operator
      serviceAccount: benchmark-operator
      volumes:
      - name: test-volume
        hostPath:
          path: /sys/fs/XXXXXX
          type: Directory
{% endif %}
      containers:
      - name: byowl
        command: ["/bin/sh", "-c"]
        args: ["{{ workload_args.commands }}"]
        image: "{{ workload_args.image }}"
{% if workload_args.resources is defined %}
        resources: {{ workload_args.resources | to_json }}
{% endif %}
        imagePullPolicy: Always
{% if workload_args.privileged is sameas true %}
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs/XXXXXX
            name: test-volume
{% endif %}
      restartPolicy: OnFailure
{% include "metadata.yml.j2" %}
```

But this is kind of hard coded. We wanted to have some generic implementation so that anyone can add their own changes how individual wants.
As a result I had tried some new changes to make it generic:
```
apiVersion: batch/v1
kind: "job"
metadata:
  name: "byowl-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: byowl-{{ trunc_uuid }}
    spec:
{% if workload_args.runtime_class is defined %}
      runtimeClassName: "{{ workload_args.runtime_class }}"
{% if workload_args.specoptions is defined %}
{% for label, value in  workload_args.specoptions.items() %}
        {{ label }}: {{ value | to_json }}
{% endfor %}
{% endif %}
{% endif %}
      containers:
      - name: byowl
        command: ["/bin/sh", "-c"]
        args: ["{{ workload_args.commands }}"]
        image: "{{ workload_args.image }}"
        imagePullPolicy: Always
{% if workload_args.containeroptions is defined %}
{% for label, value in  workload_args.containeroptions.items() %}
        {{ label }}: {{ value | to_json }}
{% endfor %}
{% endif %}
      restartPolicy: OnFailure
```
It has two options `specoptions` and `containeroptions`. Whatever we use these options, it will go to the respective places.
I have tested this generic change does not work for all the properties:
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: byowl-benchmark-example
  namespace: my-ripsaw
spec:
  workload:
    name: byowl
    args:
      image: "XXXXXX"
      clients: 1
      commands: 'COMMAND'
      specoptions:
        serviceAccountName: benchmark-operator      # <<<< Does Not work
        serviceAccount: benchmark-operator          # <<<< Does Not work
        volumes:                                    # <<<< Does Not work
        - name: test-volume
          hostPath:
            path: '/sys/fs/XXXXXX'
            type: Directory
      containeroptions:
        securityContext:                            # <<<< Does Not work
          privileged: true
        volumeMounts:                               # <<<< Does Not work
          - mountPath: '/sys/fs/XXXXXX'
            name: test-volume
        resources:                                  # <<<< This works
          requests:
            cpu: 4000m
          limits:
            cpu: 4000m
```

You can see the yaml of the generated POD:
```
spec:
  containers:
  - args:
    - 'COMMAND'
    command:
    - /bin/sh
    - -c
    image: XXXXXX
    imagePullPolicy: Always
    name: byowl
    resources:
      limits:
        cpu: "4"
      requests:
        cpu: "4"
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000590000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-r8s9p
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-9hmnp
  nodeName: XXXXXX
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000590000
    seLinuxOptions:
      level: s0:c24,c19
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```
@rsevilla87 , it will be helpful, if you point me out what I am missing in the generic implementation, as a result other things are not working expect `resources`.

Thanks.
