### ISSUE TITLE
[RFE] Benchmark-operator should manage the lifecycle of Cerberus

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/benchmark-operator#547]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement request.

**Describe the solution you'd like**
Cerberus - https://github.com/cloud-bulldozer/cerberus is a standalone tool as and benchmark-operator today can query Cerberus provided the url over which it exposes the go/no-go signal: https://github.com/cloud-bulldozer/benchmark-operator#cerberus-integration. We need to add support to the benchmark-operator to manage the lifecycle of the Cerberus - start it before the benchmark, query it during the benchmark and stop it at the end of the benchmark run. We need to capture the report and the Cerberus database containing the metrics/failures or query for the duration of the benchmark for the json with the metrics and store them long term to refer in case we want to investigate. The Cerberus pod restarts in case of issues with the node in which it has been scheduled can be handled by using a persistent volume attached to it, this way the database can still keep track of the failures occurred before/after the restart.

**Additional context**
 This will eliminate the need to manage Cerberus externally and help with Performance/Scalability integration in other areas like origin-ci, release-ci etc. to determine pass/fail in addition to PerfScale CI.

**Comment by whitleykeith** [comment]
I think this would be best done by adding Cerberus templates in the Helm Chart and surfacing up values to control Cerberus (i.e. cerberus.enabled). It would also make it trivial to configure the operator to hit the right cerberus URL as we could have it point to the cerberus service automatically.

i.e. 

```yaml
apiVersion: v1
kind: Service
  metadata:
    name: {{ include "benchmark-operator.fullname" . }}-cerberus
```

benchmark-operator deployment
```yaml
env:
- name: CERBERUS_URL
  value: http://{{ include "benchmark-operator.fullname" . }}-cerberus.{{ .Release.Namespace }}.svc.cluster.local

```
