### ISSUE TITLE
Netperf for Network Latency measurements

### ISSUE THREAD

**Issue by asispatra** [cloud-bulldozer/benchmark-operator#558]
**Is your feature request related to a problem? Please describe.**
For network performance we have `iperf3`. It looks like using `iPerf3` we can measure `Network Bandwidth`. 
Is there a way to measure `Network Latency`?

**Describe the solution you'd like**
Can we include `Netperf` to measure `Network Latency`?
Netperf can be used for Network Bandwidth and Latency measurements.
https://hewlettpackard.github.io/netperf/
https://hewlettpackard.github.io/netperf/training/Netperf.html

**Comment by rsevilla87** [comment]
Hey @asispatra, our recommendation is to use the UPerf workload to measure network latency.
We currently support 3 types of workloads:

- stream: Streaming test. Normally used to measure bandwidth with TCP/UDP and different message sizes  
- rr: Request/response test: Transactional request and response test. Normally used to measure network latency.
- bidirec: Bidirectional network test. Meant to be used to measure bandwidth in bidirectional traffic scenarios.

With the above, I think you should consider using `rr` to measure network latency:
You reuse this CR as reference:

```yaml
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf
  namespace: my-ripsaw
spec:
  elasticsearch:
    url: <YOUR ELASTIC SEARCH INSTANCE>
    index_name: ripsaw-uperf
  metadata:
    collection: false
  cleanup: false
  workload:
    name: uperf
    args:
      hostnetwork: false
      serviceip: false
      pin: false
      multus:
        enabled: false
      samples: 2
      pair: 1
      test_types:
        - rr
      protos:
        - tcp
        - udp
      sizes:
        - 64
        - 1024
        - 16384
      nthrs:
        - 1
      runtime: 60
      debug: true
```
Find further details in the [uperf docs page](https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md)

Hope that helps
