### ISSUE TITLE
Uperf does not run properly always

### ISSUE THREAD

**Issue by asispatra** [cloud-bulldozer/benchmark-operator#567]
**Describe the bug**
While I was running uperf using benchmark operator initially once or twice run properly. After that client and server both are in running state OR only the server is running.

Really do not understand that is the issue.

Here is the yaml I am using:
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf
  namespace: my-ripsaw
spec:
  workload:
    name: uperf
    args:
      hostnetwork: false
      serviceip: false
      pin: true
      pin_server: "SERVER"
      pin_client: "CLIENT"
      samples: 1
      pair: 1
      test_types:
        - rr
      protos:
        - tcp
      sizes:
        - 1024
      nthrs:
        - 1
      runtime: 60
```

**To Reproduce**
Do not know the exact trigger point.

**Expected behavior**
1. Uperf-Server should run first.
2. Uperf-Client should run.
3. Uperf-Client Completes.
4. Uperf-Server Terminates.
