### ISSUE TITLE
trex-traffic generation pod - usage error

### ISSUE THREAD

**Issue by usunnapu** [cloud-bulldozer/benchmark-operator#576]
Looking to use this benchmark operator to validate DPDK virtual functions in OpenShift cluster v4.6. I can see the application POD is running successfully but in the trex-traffic-gen-pod, I see CrashLoopBackOff error as below
```
[core@csah dpdk]$ oc get pods
NAME                                     READY   STATUS             RESTARTS   AGE
benchmark-operator-6dbdffccb-glh2v       2/2     Running            0          30m
testpmd-application-pod-2c45ad81-jz9q8   1/1     Running            0          5m11s
trex-traffic-gen-pod-2c45ad81-h6cqn      0/1     CrashLoopBackOff   5          4m49s
```
Upon checking the logs, noticing a usage error as below
```
[core@csah dpdk]$ oc logs trex-traffic-gen-pod-2c45ad81-h6cqn
2021-05-19T20:52:46Z - INFO     - MainProcess - run_snafu: logging level is INFO
2021-05-19T20:52:46Z - INFO     - MainProcess - wrapper_factory: identified trex as the benchmark wrapper
usage: run_snafu [-h] [-v] -t TOOL [--run-id [RUN_ID]]
                 [--resourcetype RESOURCETYPE] -u UUID [--user USER]
run_snafu: error: unrecognized arguments:
```
Any thoughts or recommendations ?

**Comment by jtaleric** [comment]
Can you share the CR you passed to benchmark-operator?

**Comment by usunnapu** [comment]
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: testpmd-benchmark
  namespace: my-ripsaw
spec:
  clustername: demo
  workload:
    name: testpmd
    args:
      privileged: true
      pin: false
      pin_testpmd: "compute-1.example.lab"
      pin_trex: "compute-1.example.lab"
      networks:
        testpmd:
          - name: mellanox-dpdk-network
            count: 2  # Interface count, Min 2
        trex:
          - name: mellanox-dpdk-network
            count: 2
```
FYI. I specified the compute node name that has keys "pin_testpmd" and "pin_trex" in the above yaml file. Please let me know if thats not the intention of these keys in the above yaml file.
