### ISSUE TITLE
Almost no benchmark handles failures

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/benchmark-operator#591]
>TL;DR: A majority of the benchmarks created by the operator do not handle and report failures, leading to a lot of extra work that has to be done to actually determine status of the benchmarks in downstream projects like e2e-benchmarking.

Most of the time the benchmarks simply handle the happy path by setting the `status.complete` flag to `true` whenever the success condition is met. However, only 3 benchmarks (cyclictest, kube-burner, and oslat) actually have blocks to check for and report a Failure state. 

This causes significant issues with orchestrating multiple benchmarks because we have to figure out how each benchmark functions and write a script specifically to check for success/failure states of underlying benchmark resources. 

For example, in the `scale` benchmark there is only a block to check for the success of the underlying scale pod. Therefore if the scale job fails the Scale benchmark will stay in a Running state for an indefinite amount of time. This means that we have to write logic in a script to specifically go check the scale pod ourselves, which is exactly what happens here: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/scale-perf/run_scale_fromgit.sh

This is the case for almost every single benchmark in this repo, and thus each benchmark essentially requires a specific script solely dedicated to managing it's lifecycle (i.e. e2e-benchmarking) - something that, by definition, an [operator should manage](https://www.redhat.com/en/topics/containers/what-is-a-kubernetes-operator).

The solution is two-fold: (1) we need to actually go back and refactor all of the underlying roles to ensure they all check for Running/Complete/Failed states. (2) We need to enforce this on every new benchmark. 

I think a good option would be for us to add a block in `roles/common` that would check against a variable that each benchmark needs to define itself (i.e. kube-burner registers a variable called `job_state` to acheive this). While kube-burner's implementation of the conditionals is a bit too specific to itself, you could refactor it to something like this:  

in `roles/kube-burner/tasks/main.yaml`
```yaml

- name: Get job status
   k8s_info:
      kind: Job
      api_version: v1
      namespace: '{{ operator_namespace }}'
      name: kube-burner-{{ trunc_uuid }}
    register: job_state

# Essentially every benchmark will need to set this fact
- name: Update benchmark fact
  set_fact: 
    benchmark_status:
      complete: {{ job_state.resources[0].status.succeeded is defined or job_state.resources[0].status.failed is defined | bool }}
      state: {{ "Complete" if ((job_state.resources[0].status.succeeded | int) > 0) else "Failed" if ((job_state.resources[0].status.failed | int) > 0)

```

In `roles/common/tasks/main.yml` 
```yaml
  - name: Set complete state to benchmark
    operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Complete
        complete: true
    when: benchmark_status.complete and benchmark_status.state == "Complete"

  - name: Set failed state to benchmark
    operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Failed
        complete: true
    when: benchmark_status.complete and benchmark_status.state == "Failed"

```

With this we can write one script to wait for the `complete` bool to become true to indicate that the benchmark has finished, and then use Compete/Failed to determine if the benchmark was successful.
