### ISSUE TITLE
VM is not working in latest benchmark operator version

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#611]
**Describe the bug**
Prerequisite:
Cluster with CNV 

**To Reproduce**
1. Install benchmark-operator using helm or make deploy
2. Create file stressng_vm.yaml
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: stressng-vm-benchmark
  namespace: my-ripsaw
spec:
  system_metrics:
    collection: false
    prom_url: ""
    es_url: ""
    prom_token: ""
    metrics_profile: ""
  elasticsearch:
    url: ""
    index_name: ripsaw-stressng
  metadata:
    collection: false
  workload:
    name: stressng
    args:
      # general options
      runtype: "parallel"
      timeout: "30"
      instances: 1
      cpu_stressors: "1"
      cpu_percentage: "100"
      # vm stressor option
      vm_stressors: "1"
      vm_bytes: "128M"
      # mem stressor options
      mem_stressors: "1"
      kind: vm
      client_vm:
        dedicatedcpuplacement: false
        sockets: 1
        cores: 4
        threads: 1
        image: kubevirt/fedora-cloud-container-disk-demo:latest
        limits:
          memory: 16Gi
        requests:
          memory: 16Gi
        network:
          front_end: bridge # or masquerade
          multiqueue:
            enabled: false # if set to true, highly recommend to set selinux to permissive on the nodes where the vms would be scheduled
            queues: 0 # must be given if enabled is set to true and ideally should be set to vcpus ideally so sockets*threads*cores, your image must've ethtool installed
        extra_options:
          - none
          #- hostpassthrough
```
3. oc create -f stressng_vm.yaml
4. oc get vmi 
5. Notice that the vm is not created
This issue is appeared when installing using helm or make deploy
This issue is appeared in all the workloads that support vm: stressng_vm, uperf_vm, hammerdb_vm

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
