### ISSUE TITLE
Data did not upload to ElasticSearch

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#615]
**Describe the bug**
For every workload the data did not upload due to 'NewConnectionError'
(This issue is stated to happen in latest release)
**To Reproduce**
1. Make deploy benchmark-operator
2. Verify that ElasticSearch url is running and valid
3. oc create -f stressng.yaml

stressng.yaml
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: stressng
  namespace: benchmark-operator
spec:
  system_metrics:
    collection: false
    prom_url: ""
    es_url: ""
    prom_token: ""
    metrics_profile: ""
  elasticsearch:
    url: "** valid url **"
    index_name: stressng-pod
  metadata:
    collection: false
  workload:
    name: "stressng"
    args:
      # general options
      runtype: "parallel"
      timeout: "30"
      instances: 1
      # cpu stressor options
      cpu_stressors: "1"
      cpu_percentage: "100"
      # vm stressor option
      vm_stressors: "1"
      vm_bytes: "128M"
      # mem stressor options
      mem_stressors: "1"
```
Notice that data didnt upload to elastic search.
Got the following error:
```
2021-07-25T08:39:38Z - INFO     - MainProcess - run_snafu: Connected to the elasticsearch cluster with info as follows:
2021-07-25T08:40:29Z - WARNING  - MainProcess - run_snafu: Elasticsearch connection caused an exception: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7ff05b0d6dd8>
```

**Expected behavior**
The data should upload to elastic search properly

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
