### ISSUE TITLE
iperf3 Benchmark fails: Running benchmark of iperf3 for UDP doesn't work and Pods go in error state.  

### ISSUE THREAD

**Issue by MuhammadMunir12** [cloud-bulldozer/benchmark-operator#642]
I have run the iperf3 benchmark with default configs as mentioned in the benchmark manifest given below: 

```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: iperf3-benchmark
  namespace: my-ripsaw
spec:
  clustername: ocp-cluster
  workload:
    name: iperf3
    args:
      pairs: 1
      hostnetwork: false
      pin: true
      pin_server: "worker-1"
      pin_client: "worker-1"
      port: 5201
      transmit_type: time
      transmit_value: 60
      omit_start: 0
      length_buffer: 128K
      window_size: 64k
      ip_tos: 0
      mss: 900
      streams: 1
      extra_options_client: ' '
      extra_options_server: ' '
      #retries: 200
```

The above manifest works fine. As mentioned here: [https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/iperf.md]
When I add extra options for the client & server for UDP as "-u", both server and client pods go in an error state. Whereas, upon using "u" flag I see no difference in default (TCP) results and results with "u" flag for UDP. 

```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: iperf3-benchmark
  namespace: my-ripsaw
spec:
  clustername: r189a
  workload:
    name: iperf3
    args:
      pairs: 1
      hostnetwork: false
      pin: true
      pin_server: "worker-1"
      pin_client: "worker-1"
      port: 5201
      transmit_type: time
      transmit_value: 60
      omit_start: 0
      length_buffer: 128K
      window_size: 64k
      ip_tos: 0
      mss: 900
      streams: 1
      extra_options_client: "-u"   #or "u" 
      extra_options_server: "-u"  #or "u"
      #retries: 200

```

Could you please guide me on using the UDP-based traffic patterns iperf3 benchmark?

Also, I was not able to run iperf3 benchmark on nodes in MCP for DPDK. Is there any restriction that iperf3 benchmark could only be run on nodes with no DPDK enabled?

**Comment by jtaleric** [comment]
> https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/iperf.md



> I have run the iperf3 benchmark with default configs as mentioned in the benchmark manifest given below:
> 
> ```
> apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
> kind: Benchmark
> metadata:
>   name: iperf3-benchmark
>   namespace: my-ripsaw
> spec:
>   clustername: ocp-cluster
>   workload:
>     name: iperf3
>     args:
>       pairs: 1
>       hostnetwork: false
>       pin: true
>       pin_server: "worker-1"
>       pin_client: "worker-1"
>       port: 5201
>       transmit_type: time
>       transmit_value: 60
>       omit_start: 0
>       length_buffer: 128K
>       window_size: 64k
>       ip_tos: 0
>       mss: 900
>       streams: 1
>       extra_options_client: ' '
>       extra_options_server: ' '
>       #retries: 200
> ```
> 
> The above manifest works fine. As mentioned here: [https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/iperf.md]
> When I add extra options for the client & server for UDP as "-u", both server and client pods go in an error state. Whereas, upon using "u" flag I see no difference in default (TCP) results and results with "u" flag for UDP.

So, the `u` option works, it is when you add the `-` to the option, the pods go into error state. 

It seems like your concern is if the test is actually using UDP vs TCP, not necessarily the flag. 

> 
> ```
> apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
> kind: Benchmark
> metadata:
>   name: iperf3-benchmark
>   namespace: my-ripsaw
> spec:
>   clustername: r189a
>   workload:
>     name: iperf3
>     args:
>       pairs: 1
>       hostnetwork: false
>       pin: true
>       pin_server: "worker-1"
>       pin_client: "worker-1"
>       port: 5201
>       transmit_type: time
>       transmit_value: 60
>       omit_start: 0
>       length_buffer: 128K
>       window_size: 64k
>       ip_tos: 0
>       mss: 900
>       streams: 1
>       extra_options_client: "-u"   #or "u" 
>       extra_options_server: "-u"  #or "u"
>       #retries: 200
> ```
> 
> Could you please guide me on using the UDP-based traffic patterns iperf3 benchmark?

We don't extensively use `iperf3`, we use the `UPerf` benchmark for most of our throughput testing. 

> 
> Also, I was not able to run iperf3 benchmark on nodes in MCP for DPDK. Is there any restriction that iperf3 benchmark could only be run on nodes with no DPDK enabled?

**Comment by MuhammadMunir12** [comment]
@jtaleric But it should work at least with iperf3, isn't it? Yeah, I can understand whether it's using TCP or UDP traffic. 

You've run Uperf with the following manifest as mentioned in the benchmark's guide? 
(https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md)

Is it necessary to set up elasticsearch prior to running Uperf?

**Comment by rsevilla87** [comment]
@MuhammadMunir12 in case you're still interested in using iperf, you shouldn't set -u in `extra_options_server` in the CR.

**Comment by MuhammadMunir12** [comment]
@rsevilla87 so using only "u" sets the traffic patterns to UDP?

**Comment by rsevilla87** [comment]
> @rsevilla87 so using only "u" sets the traffic patterns to UDP?

extra_options_server and extra_options_client are passed directly to iper3 server and client respetively. And yes, -u/--udp enables UDP traffic.

```
$ iperf3 -h | grep 'udp'
  -u, --udp                 use UDP rather than TCP
```

**Comment by MuhammadMunir12** [comment]
> @jtaleric But it should work at least with iperf3, isn't it? Yeah, I can understand whether it's using TCP or UDP traffic.
> 
> You've run Uperf with the following manifest as mentioned in the benchmark's guide?
> (https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md)
> 
> Is it necessary to set up elasticsearch prior to running Uperf?

@rsevilla87  Thank you for confirming on the UDP flag. What's your opinion about this?

**Comment by rsevilla87** [comment]
> > @jtaleric But it should work at least with iperf3, isn't it? Yeah, I can understand whether it's using TCP or UDP traffic.
> > You've run Uperf with the following manifest as mentioned in the benchmark's guide?
> > (https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md)
> > Is it necessary to set up elasticsearch prior to running Uperf?
> 
> @rsevilla87 Thank you for confirming on the UDP flag. What's your opinion about this?

No it's not necessary as the iper3 workload does not index any document in ES (https://github.com/cloud-bulldozer/benchmark-operator#workloads-status), just make sure metadata collection is disabled.

**Comment by MuhammadMunir12** [comment]
@jtaleric So, how we can get to know for using "u" flag in extra_server_options and extra_client_options is changing traffic patterns to UDP? Is there any method to check it?

**Comment by jtaleric** [comment]
> @jtaleric So, how we can get to know for using "u" flag in extra_server_options and extra_client_options is changing traffic patterns to UDP? Is there any method to check it?

Other than sniffing the traffic, no? You could possibly set a ACL to drop/not-allow any TCP traffic between pods, and see if it succeeds.

**Comment by sjug** [comment]
@MuhammadMunir12 as @rsevilla87 mentioned you will only need to set `-u` for the `extra_options_client` field.

Additionally the client pod will still fail if you keep the default `length_buffer` as `128K` is not compatible with UDP.
Either modify, comment out or delete `length_buffer` from the test CR, and you're good to go.

**Comment by MuhammadMunir12** [comment]
@sjug Thank you for pointing out the length buffer parameter. I have been able to run it. 

```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: iperf3-benchmark
  namespace: my-ripsaw
spec:
  clustername: r189a
  workload:
    name: iperf3
    args:
      pairs: 1
      hostnetwork: false
      pin: true
      pin_server: "worker1"
      pin_client: "worker1"
      port: 5201
      transmit_type: time
      transmit_value: 60
      omit_start: 0
      length_buffer: 1470   #128K (default for TCP)
      window_size: 64k
      ip_tos: 0
      mss: 900
      streams: 1
      extra_options_client: "-u"
      extra_options_server: ' '
      #retries: 200
```
