### ISSUE TITLE
TestPMD benchmark - Trex pod never starts

### ISSUE THREAD

**Issue by Tan2Pi** [cloud-bulldozer/benchmark-operator#658]
**Describe the bug**
When running the TestPMD benchmark, the testpmd application pod starts, but the trex pod never does.  I believe this is due to the Elasticsearch dictionary always being defined even when it's not declared in the CR file. This leads to unexpected behavior when the trex template tries to access variables like `elasticsearch.url`. When I comment out the Elasticsearch-related stuff in the trex template, and redeploy the operator, this error goes away.
Error Snippet from benchmark-controller:  
``` 
TASK [Start TRex] ********************************
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to be in '/opt/ansible/roles/testpmd/tasks/main.yml': line 76, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Start TRex\n    ^ here\n"
}


 Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: the template file trex.yml.j2 could not be found for the lookup"
}
```  

I believe this is due to the Elasticsearch dictionary always being defined, raising the above error when rendering trex.yml.j2
Output of `oc describe <cr>`:  
```  
Spec:
  Clustername:  <cluster_name>
  Elasticsearch:
    Parallel:     false
    verify_cert:  true
  Metadata:
    Collection:      false
    Force:           false
    Image:           quay.io/cloud-bulldozer/backpack:latest
    Privileged:      false
    Serviceaccount:  default
    Ssl:             false
    Stockpile Skip Tags:
    Stockpile Tags:
      common
      k8s
      openshift
    Targeted:  true
  system_metrics:
    Collection:       false
    Image:            quay.io/cloud-bulldozer/kube-burner:latest
    index_name:       system-metrics
    metrics_profile:  node-metrics.yml
    prom_url:         https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    Step:             30s
  Workload:
    Args:
      Debug:        false
      job_timeout:  3600
      Networks:
        Testpmd:
          Count:  2
          Name:   dpdk-network
        Trex:
          Count:    2
          Name:     dpdk-network
      Pin:          true
      pin_testpmd:  <node-0>
      pin_trex:     <node-1>
      Privileged:   true
    Name:           testpmd
Status:
  Complete:        false
  system_metrics:  Not collected
Events:            <none>
```  
Actual CR file:  
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: testpmd-benchmark
  namespace: benchmark-operator
spec:
  clustername: <cluster_name>
  workload:
    name: testpmd
    args:
      privileged: true
      pin: true
      pin_testpmd: <node-0>
      pin_trex: <node-1>
      networks:
        testpmd:
          - name: dpdk-network
            count: 2  # Interface count, Min 2
        trex:
          - name: dpdk-network
            count: 2

```
