### ISSUE TITLE
[RFE] Generic pod workload

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/benchmark-operator#672]
**Is your feature request related to a problem? Please describe.**

There're several workloads that are using a very similar code base, with the only difference of the objects they deploy.
i.e
The vegeta workload consists of the following steps:
- Create configuration resources
- Create job
- Set benchmark state to Running
- Set the benchmark as complete: true when finishes

Similar steps are repeated in other workloads such as:
- scale
- log_generator
- oslat
- image_pull
- and more

**Describe the solution you'd like**
We can create a generic-workload (name TBD yet) role, able to perform these generic tasks, that way the workloads using this role will only have one task. i.e.

```yaml
- include_role:
    name: generic_workload
  vars:
    resources: [template1.yml, template2.yml]
```

generic_workload tasks.yml
```yaml
---
- block:

  - name: Creating workload resources
    k8s:
      state: present
      definition: "{{ lookup('template', item) }}"
   loop: "{{ resources }}"

  - include_role:
      name: benchmark_state
      tasks_from: set_state
    vars:
      state: Running

  when: benchmark_state.resources[0].status.state == "Building" 

- include_role:
    name: benchmark_state
    tasks_from: completed.yml
  when: benchmark_state.resources[0].status.state == "Running"```
```

Thanks to this new role we can reduce benchmark-operator code base and ease manageability.
This would be a first approximation, we'll have to decide if we want to introduce a generic pod synchronization logic to the workloads deployed by this role. (At the moment that wouldn't be required though)
