### ISSUE TITLE
Ports getting assigned incorrectly for client-server pairs in uperf workload (Multiple pairs use case)

### ISSUE THREAD

**Issue by vishnuchalla** [cloud-bulldozer/benchmark-operator#773]
**Describe the bug**

- Port number mismatch between client and server pairs in uperf. This is leading to the failures in the client execution.
- And also in the ClusterIP service when multiple pairs are created there is mismatch in the ports number being assigned leading to issues in packets transfer from client to server.

**To Reproduce**
- For without service use case run this CR
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: benchmark-operator
spec:
  clustername: myk8scluster
  elasticsearch:
    url: https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443
  #test_user: username_to_attach_to_metadata
  workload:
    # cleanup: true
    name: uperf
    args:
      serviceip: false
      hostnetwork: false
      networkpolicy: false
      multus:
        enabled: false
      pin: true
      pin_server: "ip-10-0-137-160.us-west-2.compute.internal"
      pin_client: "ip-10-0-160-15.us-west-2.compute.internal"
      samples: 1
      kind: pod
      pair: 10
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30
```
- For Usecase with a service run this CR.
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: benchmark-operator
spec:
  clustername: myk8scluster
  elasticsearch:
    url: https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443
  #test_user: username_to_attach_to_metadata
  workload:
    # cleanup: true
    name: uperf
    args:
      serviceip: true
      hostnetwork: false
      networkpolicy: false
      multus:
        enabled: false
      pin: true
      pin_server: "ip-10-0-137-160.us-west-2.compute.internal"
      pin_client: "ip-10-0-160-15.us-west-2.compute.internal"
      samples: 1
      kind: pod
      pair: 5
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30
```

**Expected behavior**
Client and Server must be communicating on the same port numbers in order for the workload to execute.

**Screenshots**
- For multiple pairs without a service use case.
  1.  <a href="https://drive.google.com/file/d/1dcOnC8wwvfHFO7Q9VTWmZ9fvnZWyYnJJ/view?usp=sharing"><img src="https://drive.google.com/file/d/1dcOnC8wwvfHFO7Q9VTWmZ9fvnZWyYnJJ/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="list of pods" /></a>
  2.  <a href="https://drive.google.com/file/d/1xwIXZqTqsQ6WNWlU63YGt77hgioCXCgY/view?usp=sharing"><img src="https://drive.google.com/file/d/1xwIXZqTqsQ6WNWlU63YGt77hgioCXCgY/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="client server ports mismatch" /></a>
  3.  <a href="https://drive.google.com/file/d/185iownwPw6Ndbzpj2__CrFncueRd0UOq/view?usp=sharing"><img src="https://drive.google.com/file/d/185iownwPw6Ndbzpj2__CrFncueRd0UOq/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="connection refused error due to ports mismatch" /></a>
In the above screenshots we have list of client server pods(1), if you consider one of the clients and check for its configuration (2) you will notice that its corresponding server pod is listening to a different port from the one client is trying to communicate. And also even if there is failure in the uperf execution (3) the client status is being marked as completed due to which this issue did not get noticed till now. Both operator and wrapper repos require code changes to bring port numbers inline and mark the correct status of the client pods after execution.

- For multiple pairs with a service use case.
  1.  <a href="https://drive.google.com/file/d/1rsSlXfJn-qyZUtUqSrCFcvvIhuGm8Z-n/view?usp=sharing"><img src="https://drive.google.com/file/d/1rsSlXfJn-qyZUtUqSrCFcvvIhuGm8Z-n/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="list of resources" /></a>
  2.  <a href="https://drive.google.com/file/d/1rHa8Ml8qkXM1_MLYLQYkMb4ZJoM8-AYL/view?usp=sharing"><img src="https://drive.google.com/file/d/1rHa8Ml8qkXM1_MLYLQYkMb4ZJoM8-AYL/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="client details that matches 30000 port which is available in service" /></a>
  3.  <a href="https://drive.google.com/file/d/1Z8D5fdcP4k6t94JmdNrVZ_i4-yg-R3fJ/view?usp=sharing"><img src="https://drive.google.com/file/d/1Z8D5fdcP4k6t94JmdNrVZ_i4-yg-R3fJ/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="client logs that is using 30000 port" /></a>
  4.  <a href="https://drive.google.com/file/d/1yfrXEWoILzQ4LDucXCuDRwJfuODkIWZo/view?usp=sharing"><img src="https://drive.google.com/file/d/1yfrXEWoILzQ4LDucXCuDRwJfuODkIWZo/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="client details that doesn't use 30000 port  which is not in the service provided" /></a>
  5.  <a href="https://drive.google.com/file/d/1If7jvQ0FMALc9h1oyBwUaAg_G-RSHO0h/view?usp=sharing"><img src="https://drive.google.com/file/d/1If7jvQ0FMALc9h1oyBwUaAg_G-RSHO0h/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="client execution failure that uses a non 30000 port which is not provided by the service" /></a>
 In the above screenshots we have a list of resources (1), if you look at any client and server trying to communicate on 30000 port(2) and (3) are running successfully but the rest of them are failing(4) and (5) because those ports are not provided by the service. So we need to bring the port numbers inline here as well
